name: Update National League calendars

on:
  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    outputs:
      changes_detected: ${{ steps.autocommit.outputs.changes_detected }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python generate_ics.py

      - id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated calendars

      - if: steps.autocommit.outputs.changes_detected == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
